version: "2.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: '216.232.184.219'
    ports:
      - "8080:80"
    
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
    environment:
      CVAT_SHARE_URL: "Mounted from /project_x/data host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/vcr/project_x/data
      o: bind
